### ISSUE TITLE
issue cross-compiling with att header file

### ISSUE THREAD

**Issue by s2c97** [jacklund/libgatt#1]
I was cross-compiling your libgatt for a MIPS processor under openWrt.  I was getting an error with the att.h header file where it could not find "bluetooth/uuid.h".  I've noticed it is the only header file that sets the path to "bluetooth/uuid.h" instead of just "uuid.h".  WIth that change it cross-compiles successfully on my side.

**Comment by balkian** [comment]
I've also had to change that include to cmake https://github.com/arnaud-ramey/libmip

**Comment by jacklund** [comment]
Should be fixed with the above PR merged
